springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
serenity.project.name = gsc

#server.address=172.31.26.153
server.port=8025
server.servlet.context-path=/api

#82.112.255.25
spring.datasource.url=jdbc:mysql://82.112.255.25:3306/gsc
spring.datasource.username=root
spring.datasource.password=200T7ya3
#spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
jwt.secret=secretkey
jwt.expiry.millisecond=2592000000

#debug=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omar.hatem1230@gmail.com
spring.mail.password=zeqfzpntnmnmfqex
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC

imgs.key = b3f704f407cf2d932b2ed5edf0496ced

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB